/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* src = "./designs/my_adder//adder.v:2.1-18.10" *)
(* top =  1  *)
(* hdlname = "adder" *)
module adder(clk, rst_n, a, b, sum);
  (* src = "./designs/my_adder//adder.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "./designs/my_adder//adder.v:4.16-4.21" *)
  input rst_n;
  wire rst_n;
  (* src = "./designs/my_adder//adder.v:5.16-5.17" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "./designs/my_adder//adder.v:6.16-6.17" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "./designs/my_adder//adder.v:7.20-7.23" *)
  output [4:0] sum;
  wire [4:0] sum;
  (* src = "./designs/my_adder//adder.v:14.14-14.19|/home/user/orfs/tools/install/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _00_;
  (* src = "./designs/my_adder//adder.v:14.14-14.19|/home/user/orfs/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _01_;
  (* src = "./designs/my_adder//adder.v:14.14-14.19|/home/user/orfs/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _02_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:6.25-6.26" *)
  wire _03_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _04_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _05_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _06_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _07_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _08_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _09_;
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "./designs/my_adder//adder.v:14.14-14.19|/home/user/orfs/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _14_;
  (* src = "./designs/my_adder//adder.v:14.14-14.19|/home/user/orfs/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _15_;
  sky130_fd_sc_hd__xor2_1 _16_ (
    .A(_04_),
    .B(_10_),
    .X(_01_)
  );
  sky130_fd_sc_hd__a21o_1 _17_ (
    .A1(_03_),
    .A2(_06_),
    .B1(_05_),
    .X(_11_)
  );
  sky130_fd_sc_hd__a21oi_2 _18_ (
    .A1(_10_),
    .A2(_11_),
    .B1(_09_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(_08_),
    .B(_12_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a21o_1 _20_ (
    .A1(_04_),
    .A2(_10_),
    .B1(_09_),
    .X(_13_)
  );
  sky130_fd_sc_hd__a21o_1 _21_ (
    .A1(_08_),
    .A2(_13_),
    .B1(_07_),
    .X(_00_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:42.31-44.12" *)
  sky130_fd_sc_hd__fa_1 _22_ (
    .A(_03_),
    .B(a[1]),
    .CIN(b[1]),
    .COUT(_04_),
    .SUM(_15_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _23_ (
    .A(a[1]),
    .B(b[1]),
    .COUT(_05_),
    .SUM(_06_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _24_ (
    .A(a[3]),
    .B(b[3]),
    .COUT(_07_),
    .SUM(_08_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _25_ (
    .A(a[2]),
    .B(b[2]),
    .COUT(_09_),
    .SUM(_10_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/user/orfs/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _26_ (
    .A(a[0]),
    .B(b[0]),
    .COUT(_03_),
    .SUM(_14_)
  );
  (* src = "./designs/my_adder//adder.v:10.3-16.6" *)
  sky130_fd_sc_hd__dfrtp_1 \sum[0]$_DFF_PN0_  (
    .CLK(clk),
    .D(_14_),
    .Q(sum[0]),
    .RESET_B(rst_n)
  );
  (* src = "./designs/my_adder//adder.v:10.3-16.6" *)
  sky130_fd_sc_hd__dfrtp_1 \sum[1]$_DFF_PN0_  (
    .CLK(clk),
    .D(_15_),
    .Q(sum[1]),
    .RESET_B(rst_n)
  );
  (* src = "./designs/my_adder//adder.v:10.3-16.6" *)
  sky130_fd_sc_hd__dfrtp_1 \sum[2]$_DFF_PN0_  (
    .CLK(clk),
    .D(_01_),
    .Q(sum[2]),
    .RESET_B(rst_n)
  );
  (* src = "./designs/my_adder//adder.v:10.3-16.6" *)
  sky130_fd_sc_hd__dfrtp_1 \sum[3]$_DFF_PN0_  (
    .CLK(clk),
    .D(_02_),
    .Q(sum[3]),
    .RESET_B(rst_n)
  );
  (* src = "./designs/my_adder//adder.v:10.3-16.6" *)
  sky130_fd_sc_hd__dfrtp_1 \sum[4]$_DFF_PN0_  (
    .CLK(clk),
    .D(_00_),
    .Q(sum[4]),
    .RESET_B(rst_n)
  );
endmodule
